// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

type DataType string

const (
	DataType_float32 DataType = "float32"
)

type DistanceMetric string

const (
	DistanceMetric_cosine    DistanceMetric = "cosine"
	DistanceMetric_euclidean DistanceMetric = "euclidean"
)

type SSEType string

const (
	SSEType_AES256  SSEType = "AES256"
	SSEType_aws_kms SSEType = "aws:kms"
)
